function(chip_8_log_options)
    message(STATUS "-----------------------------------------------------------")
    message(STATUS "Build Configuration for ${PROJECT_NAME}:")
    message(STATUS "  Build Type:           ${CMAKE_BUILD_TYPE}")
    message(STATUS "  Compiler:             ${CMAKE_CXX_COMPILER_ID} ${CMAKE_CXX_COMPILER_VERSION}")
    message(STATUS "  C++ Standard:         ${CMAKE_CXX_STANDARD}")
    message(STATUS "  Tests:                ${CHIP_8_ENABLE_TESTS}")
    message(STATUS "  Sanitizers:           ${CHIP_8_ENABLE_SANITIZERS}")
    message(STATUS "  Clang-Tidy:           ${CHIP_8_ENABLE_CLANG_TIDY}")
    if(CMAKE_TOOLCHAIN_FILE)
        message(STATUS "  Toolchain File:       ${CMAKE_TOOLCHAIN_FILE}")
    endif()
    message(STATUS "-----------------------------------------------------------")
endfunction()
